### ISSUE TITLE
create team view

### ISSUE THREAD

**Issue by jordanskole** [jordanskole/cm-admin#14]
We need a series of sub templates, similar to how we did with the company page. 

For coaches and for players we will want to integrate a select functionality, and then the option to quickly create a new coach/player. That should be broken out into a separate issue. 

**TASKS:**

- [x] Break create players and create coaches out into a seperate issue. Model after salesloft. 
- [x] Wire up to services for real data
- [x] check for the create action
- [x] link up all the buttons in the detail view

**Basic Info:**

- [x] name
- [x] age
- [x] gender
- [x] sport
- [x] address

**Registration Details:**

- [x] fee
- [x] payment options

**Suggested Products:**

- [x] break coming soon indicator out into separate issue.
